### ISSUE TITLE
code error in all .c files

### ISSUE THREAD

**Issue by Shanlovana** [greendow/SM2-signature-creation-and-verification#1]
for example:
```
	if ( error_code = sm3_digest_z(id,
	                               id_len,
				       pub_key,
				       z_digest) )
```
use "=" is an assignment statement, not a judgment statement。

**Comment by greendow** [comment]
They are not errors.

    if ( error_code = function(param1, param2, ...) )
    {
        // handle errors...
    }

    The operation is a combination of the following two steps just for simplicity:
1.     error_code  = function(param1, param2, ...) ;
2.     if ( error_code )
        {
             // handle errors...
        }
