### ISSUE TITLE
项目中的 NID_sm2

### ISSUE THREAD

**Issue by cyberwave** [greendow/SM2-signature-creation-and-verification#2]
项目中的NID_sm2未定义，应该是NID_sm2p256v1吧。望确认及答复 ，谢谢。

**Comment by greendow** [comment]
Do you really use OpenSSL 1.1.1 version?
In the source code of 'include/openssl/obj_mac.h' , you can find:

#define SN_sm2          "SM2"
#define LN_sm2          "sm2"
#define NID_sm2         1172
#define OBJ_sm2         OBJ_sm_scheme,301L

**Comment by tianlongqin** [comment]
我用的是openssl.-1.1.1d，发现NID_sm2p256v1曲线改为了NID_sm2（gmssl用的是NID_sm2p256v1）。对比了一下参数，是相同的。个人猜测是国际只认可NID_sm2p256v1曲线，所以默认NID_sm2就为NID_sm2p256v1。

**Comment by greendow** [comment]
In OpenSSL 1.1.1 serials the macro 'NID_sm2' is defined. 'NID_sm2p256v1' is not defined. The codes here have been tested with OpenSSL 1.1.1. The compatibility with GmSSL is not supported.

**Comment by hancm** [comment]
> NID_sm2
请问下用openssl1.1.1是不是就不需要用gmalg了？openssl1.1.1服务SM算法了多谢
