### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by shikaichao-hub** [greendow/SM2-signature-creation-and-verification#3]
请问该怎么编译执行呐？我一编译就出错了
![image](https://user-images.githubusercontent.com/65749168/132934225-5a24da7b-0edb-4374-8e7e-100306308f8c.png)

**Comment by greendow** [comment]
It seems that the wrong OpenSSL version is used while compiling. As far as I know, OpenSSL 1.0.2k is the default OpenSSL version included in CentOS Linux 7. The SM2 signature codes published in this repository can only work with OpenSSL 1.1.1 series. Try the following steps:
1. download OpenSSL 1.1.1 from https://www.openssl.org/ ;
2. compile OpenSSL 1.1.1 source codes;
3. complie SM2 signature codes. Don't forget to include OpenSSL 1.1.1 head files and to link OpenSSL 1.1.1 library files.
